### ISSUE TITLE
SegmentNotFoundException was raised when AWS_XRAY_SDK_ENABLED=false and use/call any method of xray_recorder

### ISSUE THREAD

**Issue by luzfcb** [aws/aws-xray-sdk-python#155]
Hello, what is the correct way to disable X-Ray SDK without having to remove from my code the calls to the xray_recorder methods?

I'm using in a Django project that runs on Lambda, however, for local development or in Codebuild, I'd like to deactivate it, but if I disable the SDK by configuring the `AWS_XRAY_SDK_ENABLED` environment variable to `false` I get this error:

```
aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open
```

My project use 
```
boto3==1.9.144
botocore==1.12.145
aws-xray-sdk==2.4.2
django==2.1.8
```

**Comment by chanchiem** [comment]
Thank you for reporting the bug! The intended behavior is to have it not throw exceptions through any calls to begin/end_segment or begin/end_subsegment no matter the order that is called.

It looks like we added this behavior in the `record_subsegment()` method here https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/recorder.py#L410 but not in the begin_subsegment method.

The solution to this would be to have the check written in `record_subsegment()` done at the `begin_subsegment()` method. We also need explicit checking for the end_segments and end_subsegment methods to ensure no exceptions are thrown.

**Comment by luzfcb** [comment]
@chanchiem AWS have any deadlines for solving problems like this? Did you have a chance to look at my pr ()? Since `aws cloudformation package` does not work properly if there are packages installed directly from github, I can not use my fork in Lambda, and this becomes a blocker for me.

**Comment by chanchiem** [comment]
Hey, I haven't had a chance to look at it yet. I'll prioritize this PR and will get it reviewed soon. Thank you very much for your contribution :)

**Comment by chanchiem** [comment]
Took a look. Made a few comments about it. It's looking great so far!

**Comment by chanchiem** [comment]
Customer Experience when SDK is disabled:
The following recorder APIs should not throw exceptions regardless of the order in which the APIs are called.
* `begin_subsegment()`
* `end_subsegment()`
* `end_segment()`
* `current_segment()`
* `current_subsegment()`

**Comment by chensjlv** [comment]
+1 for a fix

we've already forked and patched this error internally with limited understanding of how xray works internally, but we'd like to see it gets fixed officially on the AWS side.

**Comment by heitorlessa** [comment]
+1

Meanwhile this is being reviewed, I've created the following helper methods in a tracing decorator if that helps anyone:

```python
# Will no longer be needed once #155 is resolved
# https://github.com/aws/aws-xray-sdk-python/issues/155
def _create_subsegment(name=None, client=None):
    if is_trace_disabled:
        segment = DummySegment()
        subsegment = DummySubsegment(segment)
    else:
        subsegment = client.begin_subsegment(name=name)

    return subsegment


def _end_subsegment(subsegment):
    if is_trace_disabled:
        return

    subsegment.end_subsegment()
```

**Comment by Minitour** [comment]
Any updates on this?

**Comment by Kub-AT** [comment]
This same with ContextManager `capture` and `in_subsegment`

```
>>> from aws_xray_sdk.core import xray_recorder
>>> from aws_xray_sdk import global_sdk_config
>>> global_sdk_config.sdk_enabled()
False
>>> segment = xray_recorder.begin_segment('segment_name')
>>> subsegment = xray_recorder.begin_subsegment('subsegment_name')
>>> segment
<aws_xray_sdk.core.models.dummy_entities.DummySegment object at 0x7f3f220c6160>
>>> subsegment
<aws_xray_sdk.core.models.dummy_entities.DummySubsegment object at 0x7f3f220bbb00>

>>> with xray_recorder.capture('segment_name') as segment: segment.put_metadata('key', 'value')
... 
cannot find the current segment/subsegment, please make sure you have a segment open
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/aws_xray_sdk/core/models/subsegment.py", line 63, in __enter__
    name=self.name, **self.subsegment_kwargs)
  File "/usr/local/lib/python3.7/site-packages/aws_xray_sdk/core/recorder.py", line 284, in begin_subsegment
    segment = self.current_segment()
  File "/usr/local/lib/python3.7/site-packages/aws_xray_sdk/core/recorder.py", line 267, in current_segment
    entity = self.get_trace_entity()
  File "/usr/local/lib/python3.7/site-packages/aws_xray_sdk/core/recorder.py", line 369, in get_trace_entity
    return self.context.get_trace_entity()
  File "/usr/local/lib/python3.7/site-packages/aws_xray_sdk/core/context.py", line 93, in get_trace_entity
    return self.handle_context_missing()
  File "/usr/local/lib/python3.7/site-packages/aws_xray_sdk/core/context.py", line 118, in handle_context_missing
    raise SegmentNotFoundException(MISSING_SEGMENT_MSG)
aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open
```

**Comment by chanchiem** [comment]
The last portion of the fix that needs to be made is at the lower-level modules. Right now, it checks for disabling at the high level (global recorder), so any calls that are made at lower levels would throw an exception as they are not aware of the concept of disabling. The next step would be to enable the same checks and returns inside the context. There are many methods that implicitly reference this and rely on the context to return an entity.

**Comment by felipetofoli** [comment]
Hello, any updates on this?
Thanks,

**Comment by jacques-** [comment]
+1 blocking us as well.

**Comment by srprash** [comment]
Hi @felipetofoli & @jacques- 
We are working on it. Will post an update soon.

**Comment by Dunedan** [comment]
@srprash Any update on this? That's quite an annoying problem.

**Comment by srprash** [comment]
Hi everyone, this fix was released in the v2.5.0 of the SDK. Hopefully that solves your issue. 
I'm closing this one. Please feel free to reopen or create a new issue if you're still having troubles.

Thanks

**Comment by mjhanke** [comment]
I'm still seeing this error with v2.5.0 of the client (also using local/lambda django setup like OP):

```
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/mhanke/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/mhanke/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/aws_xray_sdk/ext/django/apps.py", line 27, in ready
    raise SegmentNameMissingException('Segment name is required.')
aws_xray_sdk.core.exceptions.exceptions.SegmentNameMissingException: Segment name is required.
```

**Comment by srprash** [comment]
Hi @mjhanke 
The exception that you're getting is `SegmentNameMissingException` which thrown when a Segment is created without a name. It is different from the `SegmentNotFoundException` which is throws when a Segment does not exist in the trace context.
Can you elaborate how you're configuring your django application locally with X-Ray disabled?

**Comment by mjhanke** [comment]
I'm not sure how to elaborate other than show you all `aws-xray-sdk-python` related config 😬 let me know if I can be more specific. From our django `config.py`:

```python
# Note: this are NOQA because they appear unused, but are needed to be patched
# by xray (see `patch_all` call below)
import aiobotocore  # NOQA
import aioboto3  # NOQA
import aiohttp  # NOQA
import botocore  # NOQA
import boto3  # NOQA
import http.client  # NOQA
import requests  # NOQA
from aws_xray_sdk.core import patch_all
...
INSTALLED_APPS = [
   ...,
    *(("aws_xray_sdk.ext.django",) if is_aws() else ()),
]
...
MIDDLEWARE = [
    *(("aws_xray_sdk.ext.django.middleware.XRayMiddleware",) if is_aws() else ()),
    ...
]
...
# https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python-configuration.html#xray-sdk-python-middleware-configuration-django
XRAY_RECORDER = {
    "AUTO_INSTRUMENT": True,  # Record subsegments for built-in database and template rendering operations.
    "AWS_XRAY_TRACING_NAME": os.getenv("AWS_LAMBDA_FUNCTION_NAME"),
}

# X-Ray patches: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python-patching.html
if is_aws():
    patch_all(double_patch=True)

# Use this instead of conditional middleware and app when
# https://github.com/aws/aws-xray-sdk-python/issues/155 is closed
# AWS_XRAY_SDK_ENABLED = is_aws()
```

**Comment by srprash** [comment]
Hi @mjhanke 
It seems like your issue is different than OP's. I tested a tiny django app with a similar configuration as yours and was able to reproduce the `SegmentNameMissingException` error only when I set the `"AWS_XRAY_TRACING_NAME": ''`. Can you confirm that the `AWS_LAMBDA_FUNCTION_NAME` is being set correctly? 

Also, you don't need to include all the modules if you're using `patch_all()`. The [method](https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/core/patcher.py#L47) itself patches all the supported modules.

**Comment by mjhanke** [comment]
os.getenv("AWS_LAMBDA_FUNCTION_NAME") is indeed returning `None` when running django server locally. When I set a random string as a default, I see a similar exception to OP:

```
[08:08:08] mhanke@macbook:~/src/mst/samm (aws-xray-sdk-update)$ ./samm/manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/mhanke/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/mhanke/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check_migrations()
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/core/management/base.py", line 458, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 48, in table_names
    return get_names(cursor)
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 43, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/django/db/backends/postgresql/introspection.py", line 54, in get_table_list
    """.format('c.relispartition' if self.connection.features.supports_table_partitions else 'FALSE'))
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/aws_xray_sdk/ext/django/db.py", line 24, in execute
    result = super(DjangoXRayTracedCursor, self).execute(query, *args, **kwargs)
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/aws_xray_sdk/core/models/subsegment.py", line 58, in __call__
    meta_processor=None,
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/aws_xray_sdk/core/recorder.py", line 428, in record_subsegment
    subsegment = self.begin_subsegment(name, namespace)
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/aws_xray_sdk/core/recorder.py", line 292, in begin_subsegment
    segment = self.current_segment()
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/aws_xray_sdk/core/recorder.py", line 270, in current_segment
    entity = self.get_trace_entity()
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/aws_xray_sdk/core/recorder.py", line 390, in get_trace_entity
    return self.context.get_trace_entity()
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/aws_xray_sdk/core/context.py", line 99, in get_trace_entity
    return self.handle_context_missing()
  File "/Users/mhanke/.pyenv/versions/3.6.8/envs/mst-samm/lib/python3.6/site-packages/aws_xray_sdk/core/context.py", line 124, in handle_context_missing
    raise SegmentNotFoundException(MISSING_SEGMENT_MSG)
aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open
```

Here is my updated config, [per your suggestions](https://github.com/aws/aws-xray-sdk-python/issues/155#issuecomment-626761157):

```
from aws_xray_sdk.core import patch_all
...
INSTALLED_APPS = [
   ...,
    "aws_xray_sdk.ext.django"
]
...
MIDDLEWARE = [
    "aws_xray_sdk.ext.django.middleware.XRayMiddleware",
    ...
]
...
# https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python-configuration.html#xray-sdk-python-middleware-configuration-django
XRAY_RECORDER = {
    "AUTO_INSTRUMENT": True,  # Record subsegments for built-in database and template rendering operations.
    "AWS_XRAY_TRACING_NAME": os.getenv("AWS_LAMBDA_FUNCTION_NAME", "BOGUS_LAMBDA_FUNCTION_NAME"),
}

# X-Ray patches: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python-patching.html
if is_aws():
    patch_all(double_patch=True)

AWS_XRAY_SDK_ENABLED = is_aws()
```

**Comment by srprash** [comment]
Hi @mjhanke 
I'm trying to repro the issue with a sample django app with this configuration. Will get back with an update soon.

**Comment by srprash** [comment]
Closing this issue due to inactivity. I would recommend opening a new issue to avoid the clutter in this long thread. Thanks
